### ISSUE TITLE
Clean up - Remove Feature Flags

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1672]
With `Patron`, `Bookmarks`, and `In-app review` features released to production we can now remove corresponding feature flags: IN_APP_REVIEW_ENABLED, ADD_PATRON_ENABLED and BOOKMARKS_ENABLED

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-android/issues/1673
- [ ] https://github.com/Automattic/pocket-casts-android/issues/1675
- [ ] https://github.com/Automattic/pocket-casts-android/issues/1688
```
