### ISSUE TITLE
Project: Intro Offer – 50% off first year Plus

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#1728]
### Description
- Implement Intro Offer – 50% off first year Plus

```[tasklist]
### Tasks
- [x] Update the current trial logic to be more generic
- [x] Update UI
- [x] Update user eligibility
- [x] Add Analytics
- [x] Remove subscription product test and update the intro offer ID
```

**Comment by mebarbosa** [comment]
Marking this project as `done` since we finished the development. When we decide to release this we will enable the `intro_plus_offer_enabled` feature flag in Firebase
