### ISSUE TITLE
Playback Skipping

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#1865]
Prevent the playback position from skipping while listening to a streaming episode by fully downloading it.

```[tasklist]
### Tasks
- [x] Add feature flag
- [x] Trigger a download when the user begins streaming an episode and switch to downloaded episode
- [x] Free up disk space by deleting the downloaded file when the episode ends or stopped
- [x] Revert: #1878
- [x] Implement cache using Exoplayer cache
```

**Comment by mebarbosa** [comment]
Investigation internal reference: `pdeCcb-4Gh-p2`
