### ISSUE TITLE
Android Widgets

### ISSUE THREAD

**Issue by MiSikora** [Automattic/pocket-casts-android#1992]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1984
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1985
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1991
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2019
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2020
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2024
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2027
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2031
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2038
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2040
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2041
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2043
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2096
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2129
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2130
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2132
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2133
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2134
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2136
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2137
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2138
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2140
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2162
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2190
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2202
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2215
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2216
```
