### ISSUE TITLE
Transcripts - Phase 1

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#2398]
```[tasklist]
### Tasks
- [x] https://github.com/Automattic/pocket-casts-android/pull/2399
- [x] https://github.com/Automattic/pocket-casts-android/pull/2415
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2425
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2468
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2476
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2512
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2517
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2529
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2544
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2546
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2554
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2565
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2570
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2597
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2626
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2633
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2642
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2643
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2654
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2671
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2665
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2680
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2686
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2704
- [ ] https://github.com/Automattic/pocket-casts-android/pull/2711

```

**Comment by ashiagr** [comment]
**Exploratory testing feedback**

- [ ] Sometimes old transcript from previous episode continues to display after switching to another episode with transcript (pdcxQM-3ZU-p2#comment-3110)
- [ ] Check the performance of the app when transcripts are enabled (pdcxQM-3ZU-p2#comment-3115)
- [ ] Rotating the device with auto-rotation turned ON closes the transcript screen (pdcxQM-3ZU-p2#comment-3111) - low priority

**Comment by ashiagr** [comment]
With the main tasks completed, I am closing the project.
