### ISSUE TITLE
Kids profile

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#2507]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2508
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2509
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2510
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2511
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2552
- [x] [Kids profile] Add feature flag
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2608
```
