### ISSUE TITLE
Paywall Experiments

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2610]
```[tasklist]
### Phase 1
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2609
- [x] Set up the experiment in the Firebase console
```
```[tasklist]
### Phase 2
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2630
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2629
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2624
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2628
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2627
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2631
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2676
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2675
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2709
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2710
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2625
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2749
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2719
```

```[tasklist]
### Phase 3
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2870
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2963
```
