### ISSUE TITLE
Custom Playback Settings

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#3042]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/pocket-casts-android/pull/3065
- [ ] https://github.com/Automattic/pocket-casts-android/pull/3088
- [ ] https://github.com/Automattic/pocket-casts-android/pull/3097
- [ ] ~~Reflect global settings to local settings if not applied before~~ (p1730208229140779-slack-C07QMR40VV3)
- [ ] https://github.com/Automattic/pocket-casts-android/pull/3136
- [ ] https://github.com/Automattic/pocket-casts-android/pull/3147
```
