### ISSUE TITLE
Project: End of Year

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#410]
## Description

Show end of year stats.

### Initial work

- [x] Add modal structure #413
- [x] Add stories structure #428
- [x] Add profile card structure and badge #498
- [x] Load a dummy story + add gestures #486

### Presenting and sharing Stories

- [x] Generate a story with dummy data #495
- [x] Generate an image based on the story shown #505
- [x] Share the generated image through a share sheet #505

### Stories data
- [x] Show total listening time in 2022 https://github.com/Automattic/pocket-casts-android/pull/522
- [x] Show number of different categories they’ve listened to https://github.com/Automattic/pocket-casts-android/pull/531
- [x] Show top 5 categories and how many podcasts in each of these they’ve listened to https://github.com/Automattic/pocket-casts-android/pull/531
- [x] Show total number of podcasts and episodes they’ve listened to https://github.com/Automattic/pocket-casts-android/pull/536
- [x] Show number 1 podcast for 2022 https://github.com/Automattic/pocket-casts-android/pull/537
- [x] Show top 5 podcasts of the year https://github.com/Automattic/pocket-casts-android/pull/537
- [x] Show longest episode they listened to in 2022 https://github.com/Automattic/pocket-casts-android/pull/541
- [x] Show the first and last story (with the option to replay) https://github.com/Automattic/pocket-casts-android/pull/542
- [x] Check eligibility and if the user has the whole 2022 Listening History, if not, grab their 2022 listening history from the server https://github.com/Automattic/pocket-casts-android/pull/551

#### Known Issues/ Improvements
- Check swipe down motion to close sensitivity (disabled to allow scrolling for large font size)
- [x] ~~Address podcasts tap events capture~~  Addressed in #505
- [x] ~~Address weird state noticed in https://github.com/Automattic/pocket-casts-android/pull/495#issuecomment-1292676258~~ Addressed in #505
- [x] ~~Sudden speed up in Stories~~ (noticed in #505) Addressed in https://github.com/Automattic/pocket-casts-android/pull/531

### Design

- [x] Finish the modal and profile's card design https://github.com/Automattic/pocket-casts-android/pull/552
- [x] Finish the stories view design
    - [x] Intro story https://github.com/Automattic/pocket-casts-android/pull/553
    - [x] Listening time story https://github.com/Automattic/pocket-casts-android/pull/556
    - [x] Listened categories story https://github.com/Automattic/pocket-casts-android/pull/559
    - [x] Top podcast and longest episode story https://github.com/Automattic/pocket-casts-android/pull/561
    - [x] Listened podcasts story https://github.com/Automattic/pocket-casts-android/pull/565
    - [x] Top 5 podcasts story https://github.com/Automattic/pocket-casts-android/pull/566
    - [x] Epilogue story https://github.com/Automattic/pocket-casts-android/pull/567
    - [x] Top categories story https://github.com/Automattic/pocket-casts-android/pull/579

### Listening History Sync
- [x] Integrate Listening History sync endpoint (also update listened time from [30 mins to 5 mins](https://github.com/Automattic/pocket-casts-android/pull/551#issuecomment-1305493401))
https://github.com/Automattic/pocket-casts-android/pull/562

### Misc
- [x] Sharing: text and links https://github.com/Automattic/pocket-casts-android/pull/570
- [x] Implement the flow for logged out users and add a remote feature flag to toggle this behavior https://github.com/Automattic/pocket-casts-android/pull/591

### Tracks
- [x] Add tracks https://github.com/Automattic/pocket-casts-android/pull/586

#### Low priority 
- [ ] Improve gradients
- [x] Improve line breaks in Listened podcasts story: https://github.com/Automattic/pocket-casts-android/pull/565#pullrequestreview-1178349471 Addressed in https://github.com/Automattic/pocket-casts-android/pull/589

**Comment by ashiagr** [comment]
Feedback

- [ ] I share to a Twitter DM (as opposed to a tweet), I'm not seeing the end_of_year_story_shared event getting fired - #586

**Comment by CookieyedCodes** [comment]
Same initial issue I had with iOS(since fixed), sure it's probably my most listened to in terms of episodes listened but it's definitely not by total time tabletop podcasts are long all 😅
![Screenshot_20221124-091806.jpg](https://user-images.githubusercontent.com/20846898/203745013-0e610f0a-3fe0-49e6-8daa-b99ff122de22.jpg)
![Screenshot_20221124-091812.jpg](https://user-images.githubusercontent.com/20846898/203745046-a2c4bcde-8bf2-477e-a126-6b388109d37a.jpg)

**Comment by ashiagr** [comment]
Thanks, @CookieyedCodes! 🙇‍♀️ [PR](https://github.com/Automattic/pocket-casts-android/pull/612) raised to match iOS ordering.
