### ISSUE TITLE
Project: Single Sign-On

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#569]
### Description

Allow users to sign on with their Google account. 

### Tasks
- [ ] Integrate Google Sign-In libraries into Gradle. 
- [ ] Update “Sign in or create account” page to include the “Continue with Google” button. 
- [ ] Hide the “Continue with Google” button if the user doesn’t have Google Play services.
- [ ] Link the “Continue with Google” button to the Google SSO flow.
- [ ] Improve the token refresh logic to support Google SSO.
- [ ] Add a Firebase remote config feature flag to hide the Google sign-in.
- [ ] Switch the existing username and password login to use the OAuth2 endpoints
- [ ] Store the user’s email when using Google SSO and display it on the profile tab.
- [ ] Remove “Change password” and “Change email” when using Google Sign-In
- [ ] Add analytics to the SSO flow.
- [ ] Update the account flow. Created accounts will be shown the “Select Account Type” page and then the “Account Created” page. Account logins will be taken straight to “Profile” tab.
- [ ] Change the existing username and password flow so the “Select Account Type” is after the “Create Account” page but before the “Account Created” page.
- [ ] Work out how Android Automotive is going to work.
- [ ] Test the login flow from Sonos.
- [ ] Manually test the Android app and write automated tests.

**Comment by mchowning** [comment]
> Convert "Create account or log in" to Compose.

I think the plan is to convert this screen to use the new onboarding screens, so I'm not sure converting the current create account screen to compose would be worth it.

**Comment by geekygecko** [comment]
@mchowning We still need to have these screens, right? I have nearly finished this change so hopefully we do need it. 

<img width="670" alt="Screenshot 2022-11-15 at 6 54 48 am" src="https://user-images.githubusercontent.com/308331/201758617-4537f9ce-7fb7-4e37-8052-669da7659257.png">

**Comment by mchowning** [comment]
You're right, they're more different than I was thinking. There is a lot of overlap, but they are different.

**Comment by geekygecko** [comment]
@mchowning I think are right and I was working on an old flow. 🤦‍♂️ It seems like the existing flow is getting replaced. I might work on hooking up the Continue with Google button in the new onboarding flow.

**Comment by geekygecko** [comment]
I'm going to close this project as it's really all part of the onboarding project.
