### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#752]
## Description 

- A list of recent searches will be displayed now when the user focus the search input box. 
- Whenever a user selects an item in a search results list, the selected item will be saved in the search history, and displayed in the list described in this task (p1665038946092499/1664975388.327359-slack-C03JCLLR9C3).

#### Data layer (https://github.com/Automattic/pocket-casts-android/pull/758)

- [x] Add a migration to add new search history table to the database saving:
       - search term
       and 
       - podcast uuid 
       - episode uuid
       - folder uuid 
       along with essentials details to render search history for items selected in a search results list
- [x] Add CRUD operations for search history item
   - [x] Load podcast/ episode/ folder search history item
- [x] Add delete operation for all search history items

#### Display results (https://github.com/Automattic/pocket-casts-android/pull/765)

- [x] Create a new screen to display the search history
- [x] Add selected podcast from the search results list to search history 
- [x] Add selected folder from the search results list to search history 
- [x] Add search term to search history
- [x] Show search results
- [x] Show X button + click action

#### Other
- [x] Add search history row click action ([#767](https://github.com/Automattic/pocket-casts-android/pull/767))
- [x] Show clear all button in search result header and add click action ([#767](https://github.com/Automattic/pocket-casts-android/pull/767))
- [x] Fine-tune UI ([#769](https://github.com/Automattic/pocket-casts-android/pull/769))
- [x] Add analytics ([#778](https://github.com/Automattic/pocket-casts-android/pull/778))

**Comment by ashiagr** [comment]
@BKrnk1337 yes, this will be integrated in iOS as well.

**Comment by ashiagr** [comment]
#### Todo (this will be added once episodes are supported in search results)
- [ ] Add selected episode from the search results list to search history
