### ISSUE TITLE
Inline search results, segmented by podcasts/episodes

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#787]
The search results will be divided in two areas: podcasts and episodes. Each area will display a "Show all" link that will carry the user to the podcasts/episodes search result screen.

#### View Related
- [x] Initial prep ([#789](https://github.com/Automattic/pocket-casts-android/pull/789))
    - [x] Extract existing result views to Compose
    - [x] Add feature flag to show new search results view
    - [x] Add section headers with show all buttons for new search results view
- [x] Add new podcasts results section ([#792](https://github.com/Automattic/pocket-casts-android/pull/792))
- [x] Add episodes results section ([#792](https://github.com/Automattic/pocket-casts-android/pull/792))

#### Data
- [x] Show episodes from new episode search result API ([#792](https://github.com/Automattic/pocket-casts-android/pull/792))

#### Other
- [x] Add episode to search history on episode search result row click action ([#794](https://github.com/Automattic/pocket-casts-android/pull/794))
- [x] Add subscribe click action ([#794](https://github.com/Automattic/pocket-casts-android/pull/794))
- [x] Episode history row click action ([#794](https://github.com/Automattic/pocket-casts-android/pull/794))
